name: MinecraftBingo
version: 1.0
main: nl.jophuijbers.bingo_plugin.Main
author: Jop Huijbers
api-version: 1.16

commands:
  bingo:
    description: empty
    usage: /bingo
  lobby:
    description: empty
    usage: |
      /lobby join
      /lobby leave